Support for :second when recorded_at is :utc_datetime
ZennerIoT/ex_audit pull request #62
Opened 2021-01-12 05:45 UTC by neodevelop

I've already update the README, I also think it's the solution, but in any case.

2021-03-10 09:51 UTC, narrowtux requested changes

2021-03-10 09:51 UTC, narrowtux commented on test/precision_test.exs
> +  use ExUnit.Case
I think you should set `async: false` here to prevent other tests randomly getting `precision: :microsecond`

2021-03-10 09:51 UTC, narrowtux commented on README.md
There should also be a line in the readme that documents the `precision` app env.

2021-03-20 00:48 UTC, neodevelop commented
Can you review my changes please?

2021-03-22 10:27 UTC, narrowtux commented on test/precision_test.exs
> +  test "adjust the precision to `second` in the field `recorded_at`" do
I don't see how this tests that, you've set the precision to `:microsecond` in the `setup_all` block.

2022-09-08 12:48 UTC, closed without merging